import 'package:awesome_dialog/awesome_dialog.dart';
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:wtew/config/utils/app_assets.dart';
import 'package:wtew/config/utils/app_colors.dart';
import 'package:wtew/config/utils/app_strings.dart';
import 'package:wtew/features/talks/domain/entities/activity.dart';
import 'package:wtew/features/talks/domain/entities/note.dart';
import 'package:wtew/features/talks/domain/entities/sections.dart';
import 'package:wtew/features/talks/domain/entities/smu_thought.dart';

class AppConstants {
  // database
  static const int databaseVersion = 1;
  static const String databaseName = "gpa-calculator";
  static const String databaseSemesterTableName = "semesters";
  static const String databaseColSemesterId = "id";
  static const String datableColSemesterTerm = "term";
  static const String databaseColSemesterGPA = "gpa";
  static const String databaseColSemesterCredits = "credits";

  static const String databaseSubjectTableName = "subjects";
  static const String databaseColSubjectSemesterId = "semester_id";
  static const String databaseColSubjectName = "name";
  static const String databaseColSubjectHours = "hours";
  static const String datableColSubjectGrade = "grade";

  static const SMUThoughts smu = SMUThoughts(
    title: "Grande Finale",
    description: "",
    imagePath: AppAssets.smuLogo,
  );

  static Widget buildHelpButton(BuildContext context) {
    return IconButton(
      onPressed: () => AwesomeDialog(
        context: context,
        animType: AnimType.scale,
        customHeader: Image.asset(AppAssets.smuLogoNoText),
        title: AppStrings.welcomeMessage,
        desc: AppStrings.eventDiscription,
        btnOkText: AppStrings.goToSmuPage,
        btnOkOnPress: () async {
          final link = Uri.parse(AppStrings.smuPage);
          if (await canLaunchUrl(link)) {
            await launchUrl(
              link,
              mode: LaunchMode.externalNonBrowserApplication,
            );
          }
        },
        btnOkColor: AppColors.primaryColor,
        btnCancelText: AppStrings.cancel,
        btnCancelOnPress: () {},
      ).show(),
      icon: const Icon(
        Icons.help,
        color: Colors.black,
      ),
    );
  }

  static Future<dynamic> help(BuildContext context) {
    return AwesomeDialog(
      context: context,
      animType: AnimType.scale,
      customHeader: Image.asset(AppAssets.smuLogoNoText),
      title: AppStrings.welcomeMessage,
      desc: AppStrings.eventDiscription,
      btnOkText: AppStrings.goToSmuPage,
      btnOkOnPress: () async => await launchUrl(
        Uri.parse(AppStrings.smuPage),
      ),
      btnOkColor: AppColors.primaryColor,
      btnCancelText: AppStrings.cancel,
      btnCancelOnPress: () {},
    ).show();
  }

  static void showToast({
    required String message,
    Color? color,
    ToastGravity? gravity,
  }) {
    Fluttertoast.showToast(
      msg: message,
      toastLength: Toast.LENGTH_SHORT,
      backgroundColor: color ?? AppColors.hint,
      gravity: gravity ?? ToastGravity.BOTTOM,
    );
  }
}

class TalksData22 {
  static const String sessionPlace = "K1 - Electrical Building";

  static const BaseSection subjects = Subjects(
    image: AppAssets.subjects,
    notes: [
      Note(
        id: "1",
        title: "Title",
        description: [
          "Note4",
          "Note2",
          "Note3",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
        ],
        imagePath: AppAssets.smuLogo,
      ),
    ],
    courses: [
      Activity(
        id: "1",
        order: 1,
        instructor: "Toka Ismail",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Production Course",
          description: [
            "Production is 2 hours' subject",
            "Production in not prerequisite to any other subjects",
            "Sheets and lectures will be uploaded to Google drive ",
            "Course Content <T>",
            "Manufacturing Process",
            "Engineering Materials",
            "Casting Processes",
            "Forming Processes",
            "Machining Processes",
            "Welding Processes",
            "Measurement and Quality",
            "Cost Analysis and Management Systems",
            "Tutorials & Labs<T>",
            "One tutorial every 2 weeks ",
            "The tutorial will be in the lab 'mechanical workshop'",
            "The lab coat is essential in sections ",
            "There are sheets or exercise book that will be given  to returnees and have grades on it ",
            "Lectures<T>",
            "One lecture every week ",
            "Lectures will be in halls or class",
            "Doctors will change during the semester ",
            "Course Assessment<T>",
            "Tutorials and Labs: 15 ",
            "Midterm: 25",
            "Final Exam: 60",
          ],
          imagePath: AppAssets.production,
        ),
        activityIcon: AppAssets.productionIcon,
        title: "Production",
        description: "Production",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "2",
        order: 2,
        instructor: "Rewan Maher",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Math and Mechanics",
          description: [
            "Math<T>",
            "Number of hours of material = 3 hours per semester",
            "Study: We attend the lecture and study it well  and study the important notes in it and then we solve the sheets",
            "Section : the lecture is explained in a simple way and the sheet is solved in it",
            "Quiz: It is in the section and it is 5 degrees and it is like the questions in the sheet",
            "Exams: The midterm exam is an hour and the speed must be in solving the exam and it is without calculator and  the exams of previous years must be solved before the examThe final exam is two hours and it is without a calculator too and  the two exams measure the grade of the student's understanding of the subject not memorizing the questions",
            "There are online lectures and lectures in college depending on the person understands in what way",
            "There are subjects related to math 1 like math 2 which means you must pass  math 1 in order to register math 2",
            "Entering the department is not related to your success in the math",
            "The math series continues with you I mean in math 1, math2, math 3, math 4, math 5 depending on the department you enter",
            "Mechanics<T>",
            "Number of hours of subject = 3 hours per semester",
            "Study: We attend the lecture and study it well  and  study the important notes in it and then we solve the sheets ",
            "Section : the lecture is explained in a simple way and the sheet is solved in it ",
            "Quiz: It is in the section and it is 5 degrees and it is like the questions in the sheet",
            "Exams: The midterm exam is an hour and the speed must be in solving the exam and the most important thing is to solve the questions of the exams of previous years The final exam is two hours and the two exams measure the degree of the student's understanding of the subject  not memorizing the questions and you should solve questions for previous final year exams ",
            "There are online lectures and lectures in college depending on the person understands in what way ",
            "There is subject related to mechanics 1  like mechanics 2  which means you should pass mechanics 1  to register mechanics 2",
            "Mechanics 2 curriculum linked to math 2",
          ],
          imagePath: AppAssets.mathAndMechanics,
        ),
        activityIcon: AppAssets.mathAndMechanicsIcon,
        title: "Math and Mechanics",
        description: "Math and Mechanic",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "3",
        order: 3,
        instructor: "Shahd Ashraf",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Engineering Drawing",
          description: [
            "Drawing course = 3 hours, in most of the time there is no summer course.",
            "The course consists of two parts (drawing 2/3 degree - projection 1/3 degree ).",
            "Tools:  *We will start buying them after the first section*<T>",
            "It consists of (Ruler T, Triangles, Rotring pen, Aristotle's triangle, French Curve, Compass).",
            "System of the course<T>",
            "Lecture: There is no absence and the professor will explain the course but without applications.",
            "Section: there is absence and it has the grades of the year's work and you must be aware of what you will do with the sheet.",
            "References<T>",
            "Drawing: The official page of the engineering drawing subject Faculty of Engineering Alexandria University.",
            "Projection: Descriptive Geometry Book.",
            "The first semester<T>",
            "Drawing: Geometric construction, Applications, Projections, Isometric, Conclusion of the Third Projection, Deduction of missing view",
            "Projection: definition, basics",
            "The second semester<T>",
            "Drawing: Missing view in more details, steel",
            "Projection: Sections, Conversion, Shadow, Perspective",
            "AutoCAD: explanation and application in the section and its practical exam only",
            "The relationship of drawing course and Departments<T>",
            "Electrical departments: <Computers, Communications> (Unrelated)",
            "Mechanical departments: <Mechanics, Production> (Related)",
            "Structural Sections (Civil: Steel, Architecture: Perspective and Basics of Projection but easier)",
            "Tips<T>",
            "Speed is your weapon.",
            "Practice makes perfect.",
            "Imagination is important but drawing doesn’t depend on it completely.",
          ],
          imagePath: AppAssets.drawing,
        ),
        activityIcon: AppAssets.drawingIcon,
        title: "Engineering Drawing",
        description: "Engineering Drawing",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "4",
        order: 4,
        instructor: "Rahma Ibrahim",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Chemistry",
          description: [
            "Chemistry is a 2nd term subject.",
            "It is 3 hours subject.",
            "No previous requirements.",
            "It has 1 lecture every week.",
            "It has 1 section every week.",
            "Chemistry labs are in preparatory building.",
            "You have to attend with lab coat.",
            "You have to get a lab book & lab bag.",
            "We have 4 exams (midterm/final/oral/practical)",
          ],
          imagePath: AppAssets.chemistry,
        ),
        activityIcon: AppAssets.chemistryIcon,
        title: "Chemistry",
        description: "Chemistry",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "5",
        order: 5,
        instructor: "Safaa Adel",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Humanities",
          description: [
            "Subjects that not related to engineering.",
            "In the first year we have 3 subjects from them: Human rights, History and English.",
            "All of this subject has no sections.",
            "English: is one hour subject and technical.",
            "Human rights: is zero hour subject.",
            "History: is two hours subject and has two parts one of them is Engineering History and the other one is Architectural engineering.",
            " All this subject not close any other subject.",
          ],
          imagePath: AppAssets.humanities,
        ),
        activityIcon: AppAssets.humanitiesIcon,
        title: "Humanities",
        description: "Humanities",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "6",
        order: 6,
        instructor: "Rowan Mahmoud",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Physics",
          description: [
            "You have two subject (physics 1/physics 2)",
            "Physics 1 is not prerequisite to physics 2",
            "Physics is 3 hour-subject",
            "It has 3 lectures every two weeks",
            "It has 1 section every week",
            "One week is in class and the other is in lab",
            "Physics labs are in preparatory building",
            "You have to get a lab book",
            "The lab book contains sheets and experiments",
            "We have 2 exams (oral / practical)",
            "Those exams are held near before finals",
            "Grade distribution is 60% final and 40% class work",
            "The grades will be announced on university account",
          ],
          imagePath: AppAssets.physics,
        ),
        activityIcon: AppAssets.physicsIcon,
        title: "Physics",
        description: "Physics",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
    ],
  );

  static const BaseSection comparisons = Comparisons(
    image: AppAssets.comparisons,
    notes: [
      Note(
        id: "1",
        title: "Title",
        description: [
          "Note1",
          "Note2",
          "Note3",
          "Note4a",
          "Very Looooooooooooooong Note",
          "Another Very Loooooooooooooooooooooooooooooooooooooooooooooooooooooooong Note"
        ],
        imagePath: AppAssets.smuLogo,
      ),
    ],
    comparisons: [
      Activity(
        id: "1",
        order: 1,
        instructor: "Menna Magdy",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "GSP vs SSP",
          description: [
            "General Programs<T>",
            "Computer and Systems",
            "Communications and Electronics",
            "Electrical Power and Machines",
            "Mechanical Engineering",
            "Production Engineering",
            "Architecture Engineering",
            "Civil Engineering",
            "Nuclear and Radiation",
            "Chemical Engineering",
            "Textile Engineering",
            "Naval Architecture and Marine",
            "SSP Programs<T>",
            "Computer and Communications",
            "Mechatronics and Robotics",
            "Electromechanical Engineering",
            "Biomedical Engineering",
            "Architecture and Construction",
            "Civil and Environmental Engineering",
            "Gas and Petrochemicals",
            "Offshore and Coastal Engineering",
            "Industrial and Systems Engineering ",
            "Materials Science and Engineering",
            "Main differences between GSP and SSP<T>",
            "1.	Programs<T>",
            "SSP programs are mostly a combination of courses from 2 different general programs (e.g., Computer and Communications)",
            "After prep year, the GPA you need to enroll in a program in SSP is way less than that needed to enroll in a similar program in GSP ",
            "2.	Students<T>",
            "Fewer students are there in SSP (Smaller batches)",
            "Unlike GSP, SSP students must attend their lectures and tutorials in order not to lose marks",
            "3.	Fees<T>",
            "SSP fees aren't the same as GSP fees",
            "Last year, GSP fees were about 2,200 L.E, whereas SSP fees were about 44,000 L.E. and both fees increase every year",
            "GPA discounts (up to 70%)",
            "Discounts for athletes (up to 50%)",
            "4.	Other opportunities<T>",
            "After prep year, if you're a GSP student and you didn't get the GPA needed to enroll in a program that you desired, you still have a chance to re-take some prep courses again, and get better grades so that your GPA gets higher and then you may transfer to that program",
            "Unfortunately, this opportunity isn't exactly available in SSP ",
            "5.	Language<T>",
            "Your courses will mainly be explained in English either you enroll in SSP or GSP. Exams are in English as well.",
            "6.	Exams<T>",
            "Exams aren't the same in GSP and SSP, each have their own exams",
            "GSP: Midterm, Final and sometimes there are quizzes",
            "SSP: Midterm1, Midterm2, Final and quizzes",
            "7.	Staff and Courses<T>",
            "Same subjects/courses are taught in GSP and SSP in prep year with just slight differences in the content",
            "Some courses -such as programming and chemistry- are alternately taken in first semester in GSP and second semester in SSP ",
            "Same Doctors and Teaching assistants teach in GSP and SSP in prep year",
            "Transferring from GSP to SSP and vice versa<T>",
            "During Prep year: you're allowed to transfer - with no conditions - as long as you'll do this before the Midterm Exams in the first semester",
            "After Prep year: you're allowed to transfer as long as some administration-related conditions are fulfilled (e.g., your GPA must not be less than 2)",
            "Some Programs don't accept the transfer requests (e.g., Computer and Systems/ Compu-Communications)",
            "Your GPA changes when transferring from GSP to SSP and vice versa",
          ],
          imagePath: AppAssets.gspVsSsp,
        ),
        activityIcon: AppAssets.gspVsSspIcon,
        title: "GSP vs SSP",
        description: "GSP vs SSP",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "2",
        order: 2,
        instructor: "Youssef Elmedany",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Computer vs Computer Science",
          description: [
            "Programming definition<T>",
            "it is a way of Communication with Computers to make them perform specific tasks.",
            "Programming Languages Definition<T>",
            "They are a kind of Language whose functions are as any other Language which is making Communication between two sides. In the case of programming languages, the two sides are Computers and Humans.",
            "Who is Computer Engineer<T>",
            "Computer Engineer is a general definition the person who is responsible for Design, Programming, and Testing Computer Systems, Applications, and tools in addition to their Permanent Development to have better Output.",
            "Computer & Programming Subject Details<T>",
            "It is one of the subjects present in the preparatory year with 2 Credit Hours, especially in the First semester, and consists of 100 Grades which are divided into 60 for the Final Exam and 40 for the Midterms + Labs (Sometimes for the Midterms only). The Content of the subject is about the basics of programming which is very important in using any programming Language. Besides these basics, there is a part talking about the number systems.",
            "Difference between General & SSP concerning Computer and Programming Subject<T>",
            "For the last few years, the difference was in the programming language used by doctors in that subject. In General Programs, the Doctors preferred Python to explain the basics of programming but in SSP they preferred C.in general the choice of the programming language is not related to the type of program but is related to the doctors who are teaching the subject.Note: Python and C are Programming Languages.",
            "The Difference between Faculty of Engineering & Faculty of Computer & Information concerning Subjects<T>",
            "During the First two years in both Faculties, the subjects are almost the same. Both Faculties take common Subjects Such as (Programming, Math, Physics, Data structures & Algorithms, Databases, etc……). During the Last two Years, Some Subjects are common and Some Distinguish each Faculty from the Other. Compulsory Subjects that Distinguish Faculty of Engineering for example (Computer Networks, Embedded Systems, Computer Architecture) while those that Distinguish Faculty of Computer & Information are For example (Web Programming, Automata). The Optional Subjects which are common in Both Faculties are for example (Machine Learning, Computer Vision) and those which Distinguish Faculty of Engineering are for example (IC Design, Robot’s Kinematics and Dynamics) and those which Distinguish Faculty of Computer & Information are for ex: (Cryptography).",
            "Working fields that are more required for Faculty of Engineering Graduates<T>",
            "One of the Fields that mostly Requires Engineering Graduates is The IC Design & Analysis Field. The IC is the Smallest Building Unit in any Computer or Electronic device nowadays. The Next one is One of the most Growing Fields Today and is expected to have the Highest Working Opportunities in the Future which is the Field of Artificial Intelligence and Machine Learning.The Concept of Artificial intelligence means Implementing Devices with Certain Techniques To make these devices have Some Human Characteristics.",
            "Some important Points to be mentioned before entering the Computer Field<T>",
            "Self-Learning is one of the most important skills you must Have if you want to enter that Field Especially if you want to join the Computer & Systems Department.",
            "If you managed to get the GPA required to enter the Computer & Systems Department, Make Sure you are at least Accepting the Environment of the Field and want to learn because if you joined it only because you have managed to get its GPA, you may suffer then.",
            "The Reputation of the College you Graduated from in general only helps you to pass certain Steps if you are searching for a good job but at last, if you are not enough you will not be accepted so you have always to improve yourself especially in that field which is growing day by day and remember always that the Person is the Value",
          ],
          imagePath: AppAssets.computer,
        ),
        activityIcon: AppAssets.computerIcon,
        title: "Computer vs Computer Science",
        description:
            "Difference Between Computer Engineering and Computer Science",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "3",
        order: 3,
        instructor: "Aya Ali",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Civil Work and Technical Teams",
          description: [
            "Civil Work<T>",
            "Civil is nonprofit work aims to helping others.",
            "Concentrate on your soft skills.",
            "Call opens at the vacation of the first term (or before).",
            "Organizations and logistics (OL): responsible for decoration, gifts, and hosting.",
            "Public Relations (PR): responsible for public relations, and making deals.",
            "Project and planning (PP): responsible for making sessions, presentations, and plans for new projects and events.",
            "Human resources (HC/HR): responsible for evaluating the staff's work.",
            "Media marketing (MM): responsible for making posts and marketing campaigns for any project or event.",
            "Technical Teams<T>",
            "Working on increasing your technical knowledge.",
            "Working on your hard skills.",
            "No targeted age or studying year to get in.",
            "The call opens in the summer vacation.",
            "ROV: Torpedo, Robo-Tech, MIA, Croco-marine, Aquaphoton.",
            "Flights: Alex Eagle, Lycans.",
            "Cars: Mind cloud, Robo-Tech, MIA, Tachyons, ECO-Marathon, AU-motors.",
            "Architecture and Civil: ASCE, EBC.",
            "Nontechnical teams: SPE, Science club, Meca-union, ACM, Purity, EED, Science club, N-mole.",
          ],
          imagePath: AppAssets.civilVsTech,
        ),
        activityIcon: AppAssets.civilAndTechnicalIcon,
        title: "Civil Work and Technical Teams",
        description: "Civil Work and Technical Teams",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "4",
        order: 4,
        instructor: "Nehal Osama",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Architecture",
          description: [
            "Pre-Requirements<T>",
            "1. Visual Studies (Optics)<T>",
            "Two-hour subject that is registered in the middle school year. But it is not in the summer course",
            "Course content : The basics of technical drawing and some of the technical rules are learned, but there are none",
            "Attendance system: a two-hour lecture and a one-hour session for the application each week.",
            "2. History of Architecture<T>",
            "Two-hour subject",
            "Course content: a theoretical course in which the history of architecture for previous civilizations is recognized And knowing the difference between architecture between each era and the next",
            "Attendance system: the lectures are for two hours in the stands or online",
            "Difference between Architecture Engineering Department and Fine Arts Architecture Department<T>"
                "Architecture Engineering Department<T>",
            "Specializes in designing places for the electrical and lighting systems of the building",
            "Concerned with the shape of the building, both internally and externally.",
            "Concerned with the cost of all equipment to implement the project. As he deals with all engineers from different fields. Therefore, some subjects from other departments are studied besides The main subject in the department.",
            "Fine Arts Architecture Department<T>",
            "Cares more about the shape and design of the building than the internal calculations",
            "But in terms of study, it is very similar to the Department of Architecture in the College of Engineering, but with fewer mathematical operations.",
            "Upon graduating from the Fine Arts Department of Architecture, the engineer can work in architectural offices and is very similar to the work done by the architect from the College of Engineering.",
            "have the right to register in the Syndicate of Engineers.",
            "Difference between Architecture Engineering Department and Fine Arts<T>",
            "The main subjects in the Department of Architecture<T>",
            "1. Design<T>",
            "A course with 4 hours, which is considered a foundationThe department, because it studies the shapes of buildings and how to design buildings, and this material is very important.",
            "2. Building construction<T>",
            "Studies the foundations of buildings, their types, and the materials used in Construction and method of construction",
            "3. Theoretical subjects<T>",
            "These are studied to enhance the understanding of main subjects (Design - Building).",
          ],
          imagePath: AppAssets.architecture,
        ),
        activityIcon: AppAssets.architectureIcon,
        title: "Architecture",
        description: "Architecture",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
    ],
  );

  static const BaseSection softSkills = SoftSkills(
    image: AppAssets.softSkills,
    notes: [
      Note(
        id: "1",
        title: "Title",
        description: [
          "Note1",
          "Note2",
          "Note3",
          "Note4",
          "Very Looooooooooooooong Note",
          "Another Very Loooooooooooooooooooooooooooooooooooooooooooooooooooooooong Note"
        ],
        imagePath: AppAssets.smuLogo,
      ),
    ],
    softSkills: [
      Activity(
        id: "1",
        order: 1,
        instructor: "Ranim Elgebaly",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Time Management",
          description: [
            "1.Know How You Spend Your Time<T>",
            "Did everything you needed to do get done?",
            "Which tasks require the most time?",
            "What time of day when you are most productive?",
            "Where is most of your time is devoted",
            "2. Set Priorities<T>",
            "Creating a 'to do' list is an easy way to prioritize. Whether you need a daily, weekly, or monthly list depends on your lifestyle. Be careful to keep listmaking from getting out of control. List manageable tasks rather than goals or multi-step plans. Rank the items on your “to do” list in order of priority (both important and urgent). You may choose to group items in categories such as high priority, medium priority, or low priority; number them in order of priority; or use a color-coding system. The goal is not to mark off the most items, but to mark off the highest priority items .",
            "3.Get Organized<T>",
            "Disorganization leads to poor time management. Research has shown that clutter has a strong negative impact on perceived well-being (Roster, 2016). To improve our time management, get organized",
            "4. Use a Planning Tool<T>",
            "Time Trackers – Gain an awareness of how you spend your time.",
            "Time Savers – Increase productivity and break time-wasting habits.",
            "Task Managers – Prioritize and organize tasks to improve time management.",
            "Habit Developers – Create healthy habits to encourage time management.",
            "5. Stop Procrastinating<T>",
            "10-minute technique",
            "Using favorite distractions as rewards",
            "Changing the study environment",
            "6. Avoid Multi-tasking",
            "Psychological studies have shown that multi-tasking does not save time. In fact, the opposite is often true. You lose time when switching from one task to another, resulting in a loss of productivity",
            "7. Manage Time-Wasters<T>",
            "It helps you reduce or eliminate time spent in the activities ",
            "8. Stay Healthy<T>",
            "The care and attention you give yourself is an important investment of time. Scheduling time to relax or do nothing helps you rejuvenate physically and mentally, enabling you to accomplish tasks more quickly and easily",
          ],
          imagePath: AppAssets.timeManagement,
        ),
        activityIcon: AppAssets.timeManagementIcon,
        title: "Time Management",
        description: "Time Management",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "2",
        order: 2,
        instructor: "Toqa Elbadawy",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Self Learning",
          description: [
            "The importance of self-learning<T>",
            "The academic and university curricula cannot be fully relied upon because it deals with the basics of the scientific subject only, in addition to the rapid development of science.",
            "The ability to learn anything you want in case you want to change your career or want to increase income.",
            "The lack of specialized institutions that provide all kinds of sciences or skills, or their incompatibility financially or in terms of time, if available.",
            "Advantages of self-learning<T>",
            "The ability to study what you want or need without forcing anything on you.",
            "There are no limits to learning",
            "The ability to determine the most appropriate time to learn something and how long to learn it.",
            "Save time going to learn some things somewhere in addition to saving money most of the time.",
            "Some of the certificates available on different learning platforms are accredited by international universities that can be placed in your CV and work with them.",
            "Problems faced by self-learners<T>",
            "The freedom and flexibility of self-learning often results in difficulty in identifying sources of learning.",
            "lack of commitment due to the absence of an exam or a specific semester.",
            "Lack of a clear system of learning.",
            "Lack of knowledge of ways to save and remember information.",
            "Some resources you can rely on for your learning<T>",
            "Learn with Google",
            "Udemy",
            "Coursera",
            "Edx",
            "SkillShare",
            "Lynda",
            "Crash course",
            "Udacity",
            "Resources in Arabic<T>",
            "رواق",
            "أكاديمية حسوب",
            "إدراك",
            "ندرس",
            "تصميم",
            "Advice<T>",
            "YouTube is one of the most important and largest sources to learn anything, but it does not treat all information as true.",
            "Try to use the advantages of your university email, the most important of which is providing you with some Coursera courses for free.",
            "Get to know your mind and how it thinks and always write sudden thoughts.",
            "Before you start learning anything, try to determine your current knowledge of that science.",
          ],
          imagePath: AppAssets.selfLearning,
        ),
        activityIcon: AppAssets.selfLearningIcon,
        title: "Self Learning",
        description: "Self Learning",
        date: "date",
        startTime: "startTime",
        endTime: "endTime",
        password: "",
      ),
    ],
  );

  static BaseSection gpa = GPA(
    image: AppAssets.gpa,
    notes: const [
      Note(
        id: "1",
        title: "Title",
        description: [
          "Note1",
          "Note2",
        ],
        imagePath: AppAssets.smuLogo,
      ),
    ],
    gpa: const Activity(
      id: "1",
      order: 1,
      instructor: "Youssef Ashraf",
      place: sessionPlace,
      activityType: ActivityType.session,
      note: Note(
        id: "1",
        title: "GPA Credit Hour System",
        description: [
          "With Credit hours system, the importance of the subject  is not determined by the grades of the subject,but it is determined by the number of hours of the subject.The important of subject as the number of hours increases.",
          "Summer course (3rd semester) will help, whether you are someone who wants to enroll subjects from upcoming year or someone who is late for subjects and doesn't want to be late in graduating.",
          "Subjects are divided as <T>",
          "1. Three-Credit-Hour Subjects<T>",
          "Three lectures in two weeks",
          "Math, Physics, Drawing, and Dynamics",
          "2. Two-Credit-Hour Subjects<T>",
          "One lecture in a week ",
          "Computer and Production",
          "3. One-Credit-Hour Subjects<T>",
          "One lecture in two weeks",
          "English",
          "The grade in the credit hours system is 4 gpa, how to calculate it?<T>",
          "1. Calculate point for each subject ",
          "2. Calculate GPA for semester",
          "3. Calculate CGPA",
          "Registering Subjects<T>",
          "1. full load (more than 2)",
          "Allowed to register for up to 18 hours",
          "2. over load (more than 3)",
          "Allowed to register for up to 21 hours",
          "3. half load (more than 2)",
          "Allowed to register for up to 18 hours",
        ],
        imagePath: AppAssets.gpaS,
      ),
      activityIcon: AppAssets.gpaIcon,
      title: "Credit Hour System",
      description: "Credit Hour System",
      date: "dayDate",
      startTime: "startDate",
      endTime: "endDate",
      password: "",
    ),
  );
}

class TalksData23 {
  static const String sessionPlace = "K1 - Electrical Building";

  static const BaseSection subjects = Subjects(
    image: AppAssets.subjects,
    notes: [
      Note(
        id: "1",
        title: "Title",
        description: [
          "Note4",
          "Note2",
          "Note3",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
          "Note4",
        ],
        imagePath: AppAssets.smuLogo,
      ),
    ],
    courses: [
      Activity(
        id: "1",
        order: 1,
        instructor: "Toka Ismail",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Production Course",
          description: [
            "Production is 2 hours' subject",
            "Production in not prerequisite to any other subjects",
            "Sheets and lectures will be uploaded to Google drive ",
            "Course Content <T>",
            "Manufacturing Process",
            "Engineering Materials",
            "Casting Processes",
            "Forming Processes",
            "Machining Processes",
            "Welding Processes",
            "Measurement and Quality",
            "Cost Analysis and Management Systems",
            "Tutorials & Labs<T>",
            "One tutorial every 2 weeks ",
            "The tutorial will be in the lab 'mechanical workshop'",
            "The lab coat is essential in sections ",
            "There are sheets or exercise book that will be given  to returnees and have grades on it ",
            "Lectures<T>",
            "One lecture every week ",
            "Lectures will be in halls or class",
            "Doctors will change during the semester ",
            "Course Assessment<T>",
            "Tutorials and Labs: 15 ",
            "Midterm: 25",
            "Final Exam: 60",
          ],
          imagePath: AppAssets.production,
        ),
        activityIcon: AppAssets.productionIcon,
        title: "Production",
        description: "Production",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "2",
        order: 2,
        instructor: "Rewan Maher",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Math and Mechanics",
          description: [
            "Math<T>",
            "Number of hours of material = 3 hours per semester",
            "Study: We attend the lecture and study it well  and study the important notes in it and then we solve the sheets",
            "Section : the lecture is explained in a simple way and the sheet is solved in it",
            "Quiz: It is in the section and it is 5 degrees and it is like the questions in the sheet",
            "Exams: The midterm exam is an hour and the speed must be in solving the exam and it is without calculator and  the exams of previous years must be solved before the examThe final exam is two hours and it is without a calculator too and  the two exams measure the grade of the student's understanding of the subject not memorizing the questions",
            "There are online lectures and lectures in college depending on the person understands in what way",
            "There are subjects related to math 1 like math 2 which means you must pass  math 1 in order to register math 2",
            "Entering the department is not related to your success in the math",
            "The math series continues with you I mean in math 1, math2, math 3, math 4, math 5 depending on the department you enter",
            "Mechanics<T>",
            "Number of hours of subject = 3 hours per semester",
            "Study: We attend the lecture and study it well  and  study the important notes in it and then we solve the sheets ",
            "Section : the lecture is explained in a simple way and the sheet is solved in it ",
            "Quiz: It is in the section and it is 5 degrees and it is like the questions in the sheet",
            "Exams: The midterm exam is an hour and the speed must be in solving the exam and the most important thing is to solve the questions of the exams of previous years The final exam is two hours and the two exams measure the degree of the student's understanding of the subject  not memorizing the questions and you should solve questions for previous final year exams ",
            "There are online lectures and lectures in college depending on the person understands in what way ",
            "There is subject related to mechanics 1  like mechanics 2  which means you should pass mechanics 1  to register mechanics 2",
            "Mechanics 2 curriculum linked to math 2",
          ],
          imagePath: AppAssets.mathAndMechanics,
        ),
        activityIcon: AppAssets.mathAndMechanicsIcon,
        title: "Math and Mechanics",
        description: "Math and Mechanic",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "3",
        order: 3,
        instructor: "Shahd Ashraf",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Engineering Drawing",
          description: [
            "Drawing course = 3 hours, in most of the time there is no summer course.",
            "The course consists of two parts (drawing 2/3 degree - projection 1/3 degree ).",
            "Tools:  *We will start buying them after the first section*<T>",
            "It consists of (Ruler T, Triangles, Rotring pen, Aristotle's triangle, French Curve, Compass).",
            "System of the course<T>",
            "Lecture: There is no absence and the professor will explain the course but without applications.",
            "Section: there is absence and it has the grades of the year's work and you must be aware of what you will do with the sheet.",
            "References<T>",
            "Drawing: The official page of the engineering drawing subject Faculty of Engineering Alexandria University.",
            "Projection: Descriptive Geometry Book.",
            "The first semester<T>",
            "Drawing: Geometric construction, Applications, Projections, Isometric, Conclusion of the Third Projection, Deduction of missing view",
            "Projection: definition, basics",
            "The second semester<T>",
            "Drawing: Missing view in more details, steel",
            "Projection: Sections, Conversion, Shadow, Perspective",
            "AutoCAD: explanation and application in the section and its practical exam only",
            "The relationship of drawing course and Departments<T>",
            "Electrical departments: <Computers, Communications> (Unrelated)",
            "Mechanical departments: <Mechanics, Production> (Related)",
            "Structural Sections (Civil: Steel, Architecture: Perspective and Basics of Projection but easier)",
            "Tips<T>",
            "Speed is your weapon.",
            "Practice makes perfect.",
            "Imagination is important but drawing doesn’t depend on it completely.",
          ],
          imagePath: AppAssets.drawing,
        ),
        activityIcon: AppAssets.drawingIcon,
        title: "Engineering Drawing",
        description: "Engineering Drawing",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "4",
        order: 4,
        instructor: "Rahma Ibrahim",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Chemistry",
          description: [
            "Chemistry is a 2nd term subject.",
            "It is 3 hours subject.",
            "No previous requirements.",
            "It has 1 lecture every week.",
            "It has 1 section every week.",
            "Chemistry labs are in preparatory building.",
            "You have to attend with lab coat.",
            "You have to get a lab book & lab bag.",
            "We have 4 exams (midterm/final/oral/practical)",
          ],
          imagePath: AppAssets.chemistry,
        ),
        activityIcon: AppAssets.chemistryIcon,
        title: "Chemistry",
        description: "Chemistry",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "5",
        order: 5,
        instructor: "Safaa Adel",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Humanities",
          description: [
            "Subjects that not related to engineering.",
            "In the first year we have 3 subjects from them: Human rights, History and English.",
            "All of this subject has no sections.",
            "English: is one hour subject and technical.",
            "Human rights: is zero hour subject.",
            "History: is two hours subject and has two parts one of them is Engineering History and the other one is Architectural engineering.",
            " All this subject not close any other subject.",
          ],
          imagePath: AppAssets.humanities,
        ),
        activityIcon: AppAssets.humanitiesIcon,
        title: "Humanities",
        description: "Humanities",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "6",
        order: 6,
        instructor: "Rowan Mahmoud",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Physics",
          description: [
            "You have two subject (physics 1/physics 2)",
            "Physics 1 is not prerequisite to physics 2",
            "Physics is 3 hour-subject",
            "It has 3 lectures every two weeks",
            "It has 1 section every week",
            "One week is in class and the other is in lab",
            "Physics labs are in preparatory building",
            "You have to get a lab book",
            "The lab book contains sheets and experiments",
            "We have 2 exams (oral / practical)",
            "Those exams are held near before finals",
            "Grade distribution is 60% final and 40% class work",
            "The grades will be announced on university account",
          ],
          imagePath: AppAssets.physics,
        ),
        activityIcon: AppAssets.physicsIcon,
        title: "Physics",
        description: "Physics",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
    ],
  );

  static const BaseSection comparisons = Comparisons(
    image: AppAssets.comparisons,
    notes: [
      Note(
        id: "1",
        title: "Title",
        description: [
          "Note1",
          "Note2",
          "Note3",
          "Note4a",
          "Very Looooooooooooooong Note",
          "Another Very Loooooooooooooooooooooooooooooooooooooooooooooooooooooooong Note"
        ],
        imagePath: AppAssets.smuLogo,
      ),
    ],
    comparisons: [
      Activity(
        id: "1",
        order: 1,
        instructor: "Menna Magdy",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "GSP vs SSP",
          description: [
            "General Programs<T>",
            "Computer and Systems",
            "Communications and Electronics",
            "Electrical Power and Machines",
            "Mechanical Engineering",
            "Production Engineering",
            "Architecture Engineering",
            "Civil Engineering",
            "Nuclear and Radiation",
            "Chemical Engineering",
            "Textile Engineering",
            "Naval Architecture and Marine",
            "SSP Programs<T>",
            "Computer and Communications",
            "Mechatronics and Robotics",
            "Electromechanical Engineering",
            "Biomedical Engineering",
            "Architecture and Construction",
            "Civil and Environmental Engineering",
            "Gas and Petrochemicals",
            "Offshore and Coastal Engineering",
            "Industrial and Systems Engineering ",
            "Materials Science and Engineering",
            "Main differences between GSP and SSP<T>",
            "1.	Programs<T>",
            "SSP programs are mostly a combination of courses from 2 different general programs (e.g., Computer and Communications)",
            "After prep year, the GPA you need to enroll in a program in SSP is way less than that needed to enroll in a similar program in GSP ",
            "2.	Students<T>",
            "Fewer students are there in SSP (Smaller batches)",
            "Unlike GSP, SSP students must attend their lectures and tutorials in order not to lose marks",
            "3.	Fees<T>",
            "SSP fees aren't the same as GSP fees",
            "Last year, GSP fees were about 2,200 L.E, whereas SSP fees were about 44,000 L.E. and both fees increase every year",
            "GPA discounts (up to 70%)",
            "Discounts for athletes (up to 50%)",
            "4.	Other opportunities<T>",
            "After prep year, if you're a GSP student and you didn't get the GPA needed to enroll in a program that you desired, you still have a chance to re-take some prep courses again, and get better grades so that your GPA gets higher and then you may transfer to that program",
            "Unfortunately, this opportunity isn't exactly available in SSP ",
            "5.	Language<T>",
            "Your courses will mainly be explained in English either you enroll in SSP or GSP. Exams are in English as well.",
            "6.	Exams<T>",
            "Exams aren't the same in GSP and SSP, each have their own exams",
            "GSP: Midterm, Final and sometimes there are quizzes",
            "SSP: Midterm1, Midterm2, Final and quizzes",
            "7.	Staff and Courses<T>",
            "Same subjects/courses are taught in GSP and SSP in prep year with just slight differences in the content",
            "Some courses -such as programming and chemistry- are alternately taken in first semester in GSP and second semester in SSP ",
            "Same Doctors and Teaching assistants teach in GSP and SSP in prep year",
            "Transferring from GSP to SSP and vice versa<T>",
            "During Prep year: you're allowed to transfer - with no conditions - as long as you'll do this before the Midterm Exams in the first semester",
            "After Prep year: you're allowed to transfer as long as some administration-related conditions are fulfilled (e.g., your GPA must not be less than 2)",
            "Some Programs don't accept the transfer requests (e.g., Computer and Systems/ Compu-Communications)",
            "Your GPA changes when transferring from GSP to SSP and vice versa",
          ],
          imagePath: AppAssets.gspVsSsp,
        ),
        activityIcon: AppAssets.gspVsSspIcon,
        title: "GSP vs SSP",
        description: "GSP vs SSP",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "2",
        order: 2,
        instructor: "Youssef Elmedany",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Computer vs Computer Science",
          description: [
            "Programming definition<T>",
            "it is a way of Communication with Computers to make them perform specific tasks.",
            "Programming Languages Definition<T>",
            "They are a kind of Language whose functions are as any other Language which is making Communication between two sides. In the case of programming languages, the two sides are Computers and Humans.",
            "Who is Computer Engineer<T>",
            "Computer Engineer is a general definition the person who is responsible for Design, Programming, and Testing Computer Systems, Applications, and tools in addition to their Permanent Development to have better Output.",
            "Computer & Programming Subject Details<T>",
            "It is one of the subjects present in the preparatory year with 2 Credit Hours, especially in the First semester, and consists of 100 Grades which are divided into 60 for the Final Exam and 40 for the Midterms + Labs (Sometimes for the Midterms only). The Content of the subject is about the basics of programming which is very important in using any programming Language. Besides these basics, there is a part talking about the number systems.",
            "Difference between General & SSP concerning Computer and Programming Subject<T>",
            "For the last few years, the difference was in the programming language used by doctors in that subject. In General Programs, the Doctors preferred Python to explain the basics of programming but in SSP they preferred C.in general the choice of the programming language is not related to the type of program but is related to the doctors who are teaching the subject.Note: Python and C are Programming Languages.",
            "The Difference between Faculty of Engineering & Faculty of Computer & Information concerning Subjects<T>",
            "During the First two years in both Faculties, the subjects are almost the same. Both Faculties take common Subjects Such as (Programming, Math, Physics, Data structures & Algorithms, Databases, etc……). During the Last two Years, Some Subjects are common and Some Distinguish each Faculty from the Other. Compulsory Subjects that Distinguish Faculty of Engineering for example (Computer Networks, Embedded Systems, Computer Architecture) while those that Distinguish Faculty of Computer & Information are For example (Web Programming, Automata). The Optional Subjects which are common in Both Faculties are for example (Machine Learning, Computer Vision) and those which Distinguish Faculty of Engineering are for example (IC Design, Robot’s Kinematics and Dynamics) and those which Distinguish Faculty of Computer & Information are for ex: (Cryptography).",
            "Working fields that are more required for Faculty of Engineering Graduates<T>",
            "One of the Fields that mostly Requires Engineering Graduates is The IC Design & Analysis Field. The IC is the Smallest Building Unit in any Computer or Electronic device nowadays. The Next one is One of the most Growing Fields Today and is expected to have the Highest Working Opportunities in the Future which is the Field of Artificial Intelligence and Machine Learning.The Concept of Artificial intelligence means Implementing Devices with Certain Techniques To make these devices have Some Human Characteristics.",
            "Some important Points to be mentioned before entering the Computer Field<T>",
            "Self-Learning is one of the most important skills you must Have if you want to enter that Field Especially if you want to join the Computer & Systems Department.",
            "If you managed to get the GPA required to enter the Computer & Systems Department, Make Sure you are at least Accepting the Environment of the Field and want to learn because if you joined it only because you have managed to get its GPA, you may suffer then.",
            "The Reputation of the College you Graduated from in general only helps you to pass certain Steps if you are searching for a good job but at last, if you are not enough you will not be accepted so you have always to improve yourself especially in that field which is growing day by day and remember always that the Person is the Value",
          ],
          imagePath: AppAssets.computer,
        ),
        activityIcon: AppAssets.computerIcon,
        title: "Computer vs Computer Science",
        description:
            "Difference Between Computer Engineering and Computer Science",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "3",
        order: 3,
        instructor: "Aya Ali",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Civil Work and Technical Teams",
          description: [
            "Civil Work<T>",
            "Civil is nonprofit work aims to helping others.",
            "Concentrate on your soft skills.",
            "Call opens at the vacation of the first term (or before).",
            "Organizations and logistics (OL): responsible for decoration, gifts, and hosting.",
            "Public Relations (PR): responsible for public relations, and making deals.",
            "Project and planning (PP): responsible for making sessions, presentations, and plans for new projects and events.",
            "Human resources (HC/HR): responsible for evaluating the staff's work.",
            "Media marketing (MM): responsible for making posts and marketing campaigns for any project or event.",
            "Technical Teams<T>",
            "Working on increasing your technical knowledge.",
            "Working on your hard skills.",
            "No targeted age or studying year to get in.",
            "The call opens in the summer vacation.",
            "ROV: Torpedo, Robo-Tech, MIA, Croco-marine, Aquaphoton.",
            "Flights: Alex Eagle, Lycans.",
            "Cars: Mind cloud, Robo-Tech, MIA, Tachyons, ECO-Marathon, AU-motors.",
            "Architecture and Civil: ASCE, EBC.",
            "Nontechnical teams: SPE, Science club, Meca-union, ACM, Purity, EED, Science club, N-mole.",
          ],
          imagePath: AppAssets.civilVsTech,
        ),
        activityIcon: AppAssets.civilAndTechnicalIcon,
        title: "Civil Work and Technical Teams",
        description: "Civil Work and Technical Teams",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "4",
        order: 4,
        instructor: "Nehal Osama",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Architecture",
          description: [
            "Pre-Requirements<T>",
            "1. Visual Studies (Optics)<T>",
            "Two-hour subject that is registered in the middle school year. But it is not in the summer course",
            "Course content : The basics of technical drawing and some of the technical rules are learned, but there are none",
            "Attendance system: a two-hour lecture and a one-hour session for the application each week.",
            "2. History of Architecture<T>",
            "Two-hour subject",
            "Course content: a theoretical course in which the history of architecture for previous civilizations is recognized And knowing the difference between architecture between each era and the next",
            "Attendance system: the lectures are for two hours in the stands or online",
            "Difference between Architecture Engineering Department and Fine Arts Architecture Department<T>"
                "Architecture Engineering Department<T>",
            "Specializes in designing places for the electrical and lighting systems of the building",
            "Concerned with the shape of the building, both internally and externally.",
            "Concerned with the cost of all equipment to implement the project. As he deals with all engineers from different fields. Therefore, some subjects from other departments are studied besides The main subject in the department.",
            "Fine Arts Architecture Department<T>",
            "Cares more about the shape and design of the building than the internal calculations",
            "But in terms of study, it is very similar to the Department of Architecture in the College of Engineering, but with fewer mathematical operations.",
            "Upon graduating from the Fine Arts Department of Architecture, the engineer can work in architectural offices and is very similar to the work done by the architect from the College of Engineering.",
            "have the right to register in the Syndicate of Engineers.",
            "Difference between Architecture Engineering Department and Fine Arts<T>",
            "The main subjects in the Department of Architecture<T>",
            "1. Design<T>",
            "A course with 4 hours, which is considered a foundationThe department, because it studies the shapes of buildings and how to design buildings, and this material is very important.",
            "2. Building construction<T>",
            "Studies the foundations of buildings, their types, and the materials used in Construction and method of construction",
            "3. Theoretical subjects<T>",
            "These are studied to enhance the understanding of main subjects (Design - Building).",
          ],
          imagePath: AppAssets.architecture,
        ),
        activityIcon: AppAssets.architectureIcon,
        title: "Architecture",
        description: "Architecture",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
    ],
  );

  static const BaseSection softSkills = SoftSkills(
    image: AppAssets.softSkills,
    notes: [
      Note(
        id: "1",
        title: "Title",
        description: [
          "Note1",
          "Note2",
          "Note3",
          "Note4",
          "Very Looooooooooooooong Note",
          "Another Very Loooooooooooooooooooooooooooooooooooooooooooooooooooooooong Note"
        ],
        imagePath: AppAssets.smuLogo,
      ),
    ],
    softSkills: [
      Activity(
        id: "1",
        order: 1,
        instructor: "Ranim Elgebaly",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Time Management",
          description: [
            "1.Know How You Spend Your Time<T>",
            "Did everything you needed to do get done?",
            "Which tasks require the most time?",
            "What time of day when you are most productive?",
            "Where is most of your time is devoted",
            "2. Set Priorities<T>",
            "Creating a 'to do' list is an easy way to prioritize. Whether you need a daily, weekly, or monthly list depends on your lifestyle. Be careful to keep listmaking from getting out of control. List manageable tasks rather than goals or multi-step plans. Rank the items on your “to do” list in order of priority (both important and urgent). You may choose to group items in categories such as high priority, medium priority, or low priority; number them in order of priority; or use a color-coding system. The goal is not to mark off the most items, but to mark off the highest priority items .",
            "3.Get Organized<T>",
            "Disorganization leads to poor time management. Research has shown that clutter has a strong negative impact on perceived well-being (Roster, 2016). To improve our time management, get organized",
            "4. Use a Planning Tool<T>",
            "Time Trackers – Gain an awareness of how you spend your time.",
            "Time Savers – Increase productivity and break time-wasting habits.",
            "Task Managers – Prioritize and organize tasks to improve time management.",
            "Habit Developers – Create healthy habits to encourage time management.",
            "5. Stop Procrastinating<T>",
            "10-minute technique",
            "Using favorite distractions as rewards",
            "Changing the study environment",
            "6. Avoid Multi-tasking",
            "Psychological studies have shown that multi-tasking does not save time. In fact, the opposite is often true. You lose time when switching from one task to another, resulting in a loss of productivity",
            "7. Manage Time-Wasters<T>",
            "It helps you reduce or eliminate time spent in the activities ",
            "8. Stay Healthy<T>",
            "The care and attention you give yourself is an important investment of time. Scheduling time to relax or do nothing helps you rejuvenate physically and mentally, enabling you to accomplish tasks more quickly and easily",
          ],
          imagePath: AppAssets.timeManagement,
        ),
        activityIcon: AppAssets.timeManagementIcon,
        title: "Time Management",
        description: "Time Management",
        date: "dayDate",
        startTime: "startDate",
        endTime: "endDate",
        password: "",
      ),
      Activity(
        id: "2",
        order: 2,
        instructor: "Toqa Elbadawy",
        place: sessionPlace,
        activityType: ActivityType.session,
        note: Note(
          id: "1",
          title: "Self Learning",
          description: [
            "The importance of self-learning<T>",
            "The academic and university curricula cannot be fully relied upon because it deals with the basics of the scientific subject only, in addition to the rapid development of science.",
            "The ability to learn anything you want in case you want to change your career or want to increase income.",
            "The lack of specialized institutions that provide all kinds of sciences or skills, or their incompatibility financially or in terms of time, if available.",
            "Advantages of self-learning<T>",
            "The ability to study what you want or need without forcing anything on you.",
            "There are no limits to learning",
            "The ability to determine the most appropriate time to learn something and how long to learn it.",
            "Save time going to learn some things somewhere in addition to saving money most of the time.",
            "Some of the certificates available on different learning platforms are accredited by international universities that can be placed in your CV and work with them.",
            "Problems faced by self-learners<T>",
            "The freedom and flexibility of self-learning often results in difficulty in identifying sources of learning.",
            "lack of commitment due to the absence of an exam or a specific semester.",
            "Lack of a clear system of learning.",
            "Lack of knowledge of ways to save and remember information.",
            "Some resources you can rely on for your learning<T>",
            "Learn with Google",
            "Udemy",
            "Coursera",
            "Edx",
            "SkillShare",
            "Lynda",
            "Crash course",
            "Udacity",
            "Resources in Arabic<T>",
            "رواق",
            "أكاديمية حسوب",
            "إدراك",
            "ندرس",
            "تصميم",
            "Advice<T>",
            "YouTube is one of the most important and largest sources to learn anything, but it does not treat all information as true.",
            "Try to use the advantages of your university email, the most important of which is providing you with some Coursera courses for free.",
            "Get to know your mind and how it thinks and always write sudden thoughts.",
            "Before you start learning anything, try to determine your current knowledge of that science.",
          ],
          imagePath: AppAssets.selfLearning,
        ),
        activityIcon: AppAssets.selfLearningIcon,
        title: "Self Learning",
        description: "Self Learning",
        date: "date",
        startTime: "startTime",
        endTime: "endTime",
        password: "",
      ),
    ],
  );

  static BaseSection gpa = GPA(
    image: AppAssets.gpa,
    notes: const [
      Note(
        id: "1",
        title: "Title",
        description: [
          "Note1",
          "Note2",
        ],
        imagePath: AppAssets.smuLogo,
      ),
    ],
    gpa: const Activity(
      id: "1",
      order: 1,
      instructor: "Youssef Ashraf",
      place: sessionPlace,
      activityType: ActivityType.session,
      note: Note(
        id: "1",
        title: "GPA Credit Hour System",
        description: [
          "With Credit hours system, the importance of the subject  is not determined by the grades of the subject,but it is determined by the number of hours of the subject.The important of subject as the number of hours increases.",
          "Summer course (3rd semester) will help, whether you are someone who wants to enroll subjects from upcoming year or someone who is late for subjects and doesn't want to be late in graduating.",
          "Subjects are divided as <T>",
          "1. Three-Credit-Hour Subjects<T>",
          "Three lectures in two weeks",
          "Math, Physics, Drawing, and Dynamics",
          "2. Two-Credit-Hour Subjects<T>",
          "One lecture in a week ",
          "Computer and Production",
          "3. One-Credit-Hour Subjects<T>",
          "One lecture in two weeks",
          "English",
          "The grade in the credit hours system is 4 gpa, how to calculate it?<T>",
          "1. Calculate point for each subject ",
          "2. Calculate GPA for semester",
          "3. Calculate CGPA",
          "Registering Subjects<T>",
          "1. full load (more than 2)",
          "Allowed to register for up to 18 hours",
          "2. over load (more than 3)",
          "Allowed to register for up to 21 hours",
          "3. half load (more than 2)",
          "Allowed to register for up to 18 hours",
        ],
        imagePath: AppAssets.gpaS,
      ),
      activityIcon: AppAssets.gpaIcon,
      title: "Credit Hour System",
      description: "Credit Hour System",
      date: "dayDate",
      startTime: "startDate",
      endTime: "endDate",
      password: "",
    ),
  );
}
